#define BYTE_MAX 255
#define KILO_BYTE_MAX 1024
#define AUTH_TAG_SIZE 16
#define PUBLIC_KEY_SIZE 32
#define ENCRYPTED_PAYLOAD_SIZE 1024
#define NONCE_SIZE 16

enum UartFrameConstants
{
    UART_FRAME_HEADER_1 = 0xAB,
    UART_FRAME_HEADER_2 = 0xCD,
    UART_FRAME_TRAILER_1 = 0xE1,
    UART_FRAME_TRAILER_2 = 0xE2
};

enum Dummy
{
    DUMMY = 0x00
};

enum UartTimer
{
    UART_FRAME_TIMEOUT_MS = 100
};

enum UartParserState
{
    VERIFY_HEADER_1_BYTE,
    VERIFY_HEADER_2_BYTE,
    WAIT_FOR_DATA_LENGTH_1_BYTE,
    WAIT_FOR_DATA_LENGTH_2_BYTE,
    RECEIVE_DATA,
    VERIFY_TRAILER_1_BYTE,
    VERIFY_TRAILER_2_BYTE,
    WAIT_FOR_CRC_1_BYTE,
    WAIT_FOR_CRC_2_BYTE,
    VERIFY_CRC,
    FRAME_COMPLETE,
    FRAME_ERROR
};

enum ServerFrameConstants
{
    SERVER_FRAME_PREAMBLE = 0xABCD,
    SERVER_FRAME_IDENTIFIER_ID = 0x16050910,
    SERVER_FRAME_PACKET_TYPE = 0x01,
    SERVER_FRAME_SEQUENCE_NUMBER = 0x0001,
    SERVER_FRAME_AUTH_TAG = 0x01
};