#ifndef SETUP_NUMBER_HELPER_HPP
#define SETUP_NUMBER_HELPER_HPP

#define __AIOT_FOR_MEDTECH_DESLAB__ delay(500)
#define __SLIGHT_DELAY__ delay(1)
#define __NORMAL_DELAY__ delay(10)
#define __LONG_DELAY__ delay(30)
#define __VERY_LONG_DELAY__ delay(2000)
#define __WAIT_STATE_FOR_SERVER_PROCESSING_KEY__ delay(10)
#define IDENTIFIER_ID_STM_SIZE 4
#define FOREVER_LOOP while(1)

#define MAX_FREQUENCY 240
#define NORMAL_FREQUENCY 80
#define LOW_FREQUENCY 40
#define METRICS_SIZE 3

#define MILI_MINUTE 60000
#define MILI_HALF_MINUTE 30000
#define VERY_FAST_MILI 10000

#pragma once

enum Serial
{
    BAUD_RATE = 115200,
    TX_PIN = 16,
    RX_PIN = 17,
};

enum TransmissionState
{
    TRANSMISSION_IDLE,
    WAIT_STATE_FOR_SERVER_PROCESSING_KEY,
    TRIGGER_SIGNAL,
    PROCESS_FRAME_PARSING,
    HANDSHAKE_AND_KEY_EXCHANGE,
    PROCESS_ENCRYPTION,
    SEND_DATA_TO_SERVER,
    WAIT_FOR_ACK_PACKAGE,
    TRANSMISSION_COMPLETE,
    TRANSMISSION_ERROR
};

enum Device
{
    Identifier = 0x01,
    BYTE_LENGTH = 4
};

extern uint8_t IdentifierIDSTM[IDENTIFIER_ID_STM_SIZE];

#endif // SETUP_NUMBER_HELPER_HPP
